[versions]

androidCompileSdk = "34"
androidMinSdk = "21"
androidTargetSdk = "33"

androidGradlePlugin = "8.1.1"
kotlin = "1.9.0"

composeBom = "2023.08.00"
composeCompiler = "1.5.2"

[libraries]

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"

junit = "junit:junit:4.13.2"
androidx-test-ext-junit = "androidx.test.ext:junit:1.1.5"
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"

[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
